version: '3'
services:
  web:
    build: site
    ports :
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
      - ./vendor:/var/www/vendor   
    networks:
      - mynetwork

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: cinerater-db
      POSTGRES_USER: adam
      POSTGRES_PASSWORD: el-reverso
    ports:
      - "5432:5432"
    volumes:
      - ./server/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - mynetwork

  phppgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adamgarchi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: el-reverso
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - mynetwork

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI to view emails
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge
