version: '3'
services:
  web:
    build: site
    ports :
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: cinerater-db
      POSTGRES_USER: adam
      POSTGRES_PASSWORD: el-reverso
    networks:
      - mynetwork

  phppgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adamgarchi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: el-reverso
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - mynetwork    
      
networks:
  mynetwork:
    driver: bridge
