/:
  controller: Main
  action : home

/design-guide:
  controller: Main
  action : designGuide

/register:
  controller: SecurityController
  action : register

/login:
  controller: SecurityController
  action : login

/verification:
  controller: SecurityController
  action: verification

/verification-pending:
  controller: SecurityController
  action: verificationPending

/logout:
  controller: SecurityController
  action: logout