/:
  controller: Main
  action : home

/design-guide:
  controller: Main
  action : designGuide

/register:
  controller: SecurityController
  action : register

/login:
  controller: SecurityController
  action : login