/:
  controller: Main
  action : home

/design-guide:
  controller: Main
  action : designGuide

/register:
  controller: SecurityController
  action : register

/login:
  controller: SecurityController
  action : login

/verification:
  controller: SecurityController
  action: verification

/verification-pending:
  controller: SecurityController
  action: verificationPending

/logout:
  controller: SecurityController
  action: logout

/admin/dashboard:
  controller: AdminController
  action: index

/admin/create-user:
  controller: AdminController
  action: createUser

/admin/edit-user:
  controller: AdminController
  action: editUser

/admin/delete-user:
  controller: AdminController
  action: deleteUser

/movie/{id}:
  controller: MovieController
  action: showMovie
